import type { FlowNode } from "../FlowType";

export const nodes: Record<string, FlowNode> = {
    start: {
        id: 'start', type: 'start',
        title: 'נקודת כניסה — תסמינים ראשוניים',
        content: 'האם המטופל מציג אחד מהתסמינים הבאים בהופעה חדה ופתאומית?',
        notes: [
            'הופעה פתאומית ודרמטית של אובססיות ו/או התנהגויות כפייתיות (OCD)',
            'הופעה פתאומית של הגבלה קיצונית באכילה — כולל הפרעת ARFID',
            'הופעה פתאומית של טיקים מוטוריים ו/או קוליים',
        ],
        options: [
            { label: 'כן, אחד מהתסמינים הנ"ל קיים', nextId: 'initial_eval' },
            { label: 'יש הגבלה קיצונית באכילה / ירידה דרמטית במשקל', nextId: 'arfid_check' },
        ],
        severity: 'info',
    },
    arfid_check: {
        id: 'arfid_check', type: 'question',
        title: 'הערכת דחיפות — הגבלת אכילה (ARFID)',
        content: 'האם קיימת ירידה דרמטית במשקל או סכנת התייבשות הדורשת עירוי נוזלים (IV)?',
        options: [
            { label: 'כן — יש סכנה מיידית / ירידה קיצונית במשקל', nextId: 'hospitalize', color: 'red' },
            { label: 'לא — המצב יציב, המשך להערכה', nextId: 'initial_eval' },
        ],
        severity: 'warning',
    },
    hospitalize: {
        id: 'hospitalize', type: 'action',
        title: '🏥 שקול אשפוז דחוף',
        content: 'קיימת סכנה בשל ירידה קיצונית במשקל או התייבשות. יש לייצב את המטופל לפני המשך ההערכה.',
        actions: [
            'הערך צורך באשפוז בשל ירידת משקל חמורה',
            'הערך צורך במתן נוזלים תוך-ורידיים (IV) לייצוב',
            'לאחר ייצוב — המשך להערכה דיאגנוסטית מלאה',
        ],
        options: [{ label: 'המשך להערכה ←', nextId: 'initial_eval' }],
        severity: 'warning',
    },
    initial_eval: {
        id: 'initial_eval', type: 'action',
        title: 'הערכה ראשונית',
        content: 'שני צעדים חובה:',
        actions: [
            'תעד בפירוט את התסמינים — מתי הופיעו לראשונה, איך התפתחו, ומה השתנה בהתנהגות הילד',
            'בצע תרבית גרון לבדיקת סטרפטוקוק (GABHS) — השתמש בשני מטושים',
        ],
        options: [{ label: 'האם התסמינים הופיעו בצורה פתאומית (תוך שעות עד ימים)?', nextId: 'rapid_onset' }],
        severity: 'info',
    },
    rapid_onset: {
        id: 'rapid_onset', type: 'question',
        title: 'האם ההופעה הייתה פתאומית?',
        content: 'בדוק האם התסמינים הופיעו תוך שעות עד ימים ספורים — לא בהדרגה לאורך שבועות.',
        options: [
            { label: 'כן — הופעה פתאומית ומהירה', nextId: 'pre_pubescent' },
            { label: 'לא — הופעה הדרגתית', nextId: 'send_second_swab' },
        ],
        severity: 'info',
    },
    send_second_swab: {
        id: 'send_second_swab', type: 'action',
        title: 'בדיקות נוספות — הופעה הדרגתית',
        content: 'גם ללא הופעה פתאומית, בצע בדיקות אלו:',
        actions: [
            'שלח מטוש גרון שני לתרבית של 72 שעות',
            'הזמן בדיקות נוגדנים: ASO ו-Anti-DNase-B',
            'בדוק חשיפה לסטרפטוקוק בסביבה הקרובה — אחים, הורים, מגעים קרובים',
        ],
        options: [{ label: 'האם תרבית הגרון חיובית לסטרפטוקוק?', nextId: 'gabhs_result' }],
        severity: 'info',
    },
    gabhs_result: {
        id: 'gabhs_result', type: 'question',
        title: 'תוצאת תרבית הגרון',
        content: 'שים לב: כ-35% מהילדים לא מייצרים נוגדני ASO / Anti-DNase-B — תוצאה שלילית אינה שוללת סטרפטוקוק.',
        options: [
            { label: 'חיובי — יש סטרפטוקוק', nextId: 'pre_pubescent' },
            { label: 'שלילי — אין סטרפטוקוק', nextId: 'tics_primary' },
        ],
        severity: 'info',
    },
    tics_primary: {
        id: 'tics_primary', type: 'question',
        title: 'מה התסמין הבולט ביותר?',
        options: [
            { label: 'טיקים — הם התסמין הראשי', nextId: 'tic_disorder' },
            { label: 'אובססיות / כפייתיות / שינויים בהתנהגות', nextId: 'comorbid_check_pans' },
        ],
        severity: 'info',
    },
    tic_disorder: {
        id: 'tic_disorder', type: 'outcome',
        title: 'בדוק הפרעת טיקים',
        content: 'כאשר טיקים הם התסמין הראשי ותרבית שלילית — הערך הפרעת טיקים (כגון תסמונת טורט). בדוק גם האם קיימים תסמינים נלווים:',
        showComorbidBox: true,
        options: [
            { label: 'קיימים 2+ תסמינים נלווים בהופעה פתאומית', nextId: 'comorbid_check_pans' },
            { label: 'אין תסמינים נלווים — הפרעת טיקים בלבד', nextId: 'tic_only' },
        ],
        severity: 'warning',
    },
    tic_only: {
        id: 'tic_only', type: 'outcome',
        title: 'הפרעת טיקים — לא פאנס/פאנדס',
        content: 'טיקים בלבד ללא תסמינים נלווים — עשוי להיות הפרעת טיקים ראשונית. טפל בהתאם.',
        severity: 'info',
    },
    comorbid_check_pans: {
        id: 'comorbid_check_pans', type: 'question',
        title: 'בדיקת תסמינים נלווים — פאנס',
        content: 'האם קיימים לפחות 2 תסמינים נוירו-פסיכיאטריים נלווים בהופעה חדה וחמורה?',
        showComorbidBox: true,
        options: [
            { label: 'כן — קיימים 2 תסמינים נלווים ומעלה', nextId: 'pans_diagnosis' },
            { label: 'לא — פחות מ-2 תסמינים נלווים', nextId: 'ocd_or_arfid' },
        ],
        severity: 'info',
    },
    ocd_or_arfid: {
        id: 'ocd_or_arfid', type: 'outcome',
        title: 'ייתכן OCD / ARFID — לא פאנס',
        content: 'אין מספיק תסמינים נלווים לאבחנת פאנס. שקול אבחנה של OCD ראשוני, ARFID, או הפרעה אחרת, וטפל בהתאם.',
        severity: 'info',
    },
    pre_pubescent: {
        id: 'pre_pubescent', type: 'question',
        title: 'גיל המטופל בעת ההופעה הראשונה',
        content: 'האם המטופל היה לפני גיל ההתבגרות כאשר התסמינים הופיעו לראשונה?',
        options: [
            { label: 'כן — טרום גיל ההתבגרות', nextId: 'comorbid_check_pandas' },
            { label: 'לא / לא ידוע', nextId: 'comorbid_check_pans' },
        ],
        severity: 'info',
    },
    comorbid_check_pandas: {
        id: 'comorbid_check_pandas', type: 'question',
        title: 'בדיקת תסמינים נלווים — פאנדס',
        content: 'האם קיימים לפחות 2 תסמינים נוירו-פסיכיאטריים נלווים בהופעה חדה וחמורה?',
        showComorbidBox: true,
        options: [
            { label: 'כן — קיימים 2 תסמינים נלווים ומעלה', nextId: 'pandas_diagnosis' },
            { label: 'לא — פחות מ-2 תסמינים נלווים', nextId: 'provisional_pandas' },
        ],
        severity: 'info',
    },
    provisional_pandas: {
        id: 'provisional_pandas', type: 'outcome',
        title: 'פאנדס זמני (Provisional)',
        content: 'קיים סטרפטוקוק + הופעה פתאומית, אך אין מספיק תסמינים נלווים לאבחנה מלאה. אבחנת פאנדס זמנית — המשך מעקב. אין לדחות טיפול עד החמרה שנייה.',
        severity: 'warning',
    },
    pandas_diagnosis: {
        id: 'pandas_diagnosis', type: 'outcome',
        title: '✅ פאנס/פאנדס — עומד בקריטריונים',
        content: 'המטופל עומד בקריטריונים לאבחנת פאנס/פאנדס. קבע את חומרת המקרה ובחר פרוטוקול טיפול מתאים.',
        options: [{ label: 'המשך לקביעת חומרה ופרוטוקול טיפול ←', nextId: 'severity_assess' }],
        severity: 'success',
    },
    pans_diagnosis: {
        id: 'pans_diagnosis', type: 'action',
        title: 'הערכת פאנס — בדיקות לשלילת מצבים אחרים',
        content: 'לפני אישור האבחנה, בצע בדיקות לשלילת סיבות אחרות:',
        actions: [
            'ספירת דם מלאה עם דיפרנציאל (CBC)',
            'בדיקת נוגדנים אנטי-גרעיניים (ANA)',
            'רמות אימונוגלובולינים: IgG, IgA, IgM, IgE',
        ],
        options: [{ label: 'האם התסמינים מוסברים על ידי הפרעה נוירולוגית / רפואית ידועה אחרת?', nextId: 'known_neuro' }],
        severity: 'info',
    },
    known_neuro: {
        id: 'known_neuro', type: 'question',
        title: 'האם יש הסבר רפואי אחר?',
        content: 'בדוק האם ניתן להסביר את התסמינים על ידי הפרעה נוירולוגית ידועה — אפילפסיה, הפרעה אוטואימונית, זיהום אחר.',
        options: [
            { label: 'כן — יש הסבר רפואי אחר', nextId: 'likely_not_pans' },
            { label: 'לא — אין הסבר חלופי', nextId: 'pans_confirmed' },
        ],
        severity: 'info',
    },
    likely_not_pans: {
        id: 'likely_not_pans', type: 'outcome',
        title: 'ייתכן שאינו פאנס',
        content: 'התסמינים מוסברים על ידי הפרעה רפואית ידועה. בצע הערכה מתאימה (MRI, בדיקות דם) וטפל במצב הבסיסי.',
        severity: 'warning',
    },
    pans_confirmed: {
        id: 'pans_confirmed', type: 'outcome',
        title: '✅ פאנס מאושר',
        content: 'המטופל עומד בקריטריונים לאבחנת פאנס. המשך לקביעת חומרה ופרוטוקול טיפול.',
        options: [{ label: 'המשך לקביעת חומרה ופרוטוקול טיפול ←', nextId: 'severity_assess' }],
        severity: 'success',
    },
    severity_assess: {
        id: 'severity_assess', type: 'question',
        title: 'קביעת חומרת המקרה',
        content: 'בחר את רמת החומרה בהתאם לתיאור:',
        showSeverityScale: true,
        options: [
            { label: '🟡 קל — תסמינים בכמה שעות ביום', nextId: 'treat_mild_init', color: 'yellow' },
            { label: '🟠 בינוני — 50%–70% משעות הערות', nextId: 'treat_moderate_init', color: 'orange' },
            { label: '🔴 חמור / קיצוני — 71%–100% משעות הערות', nextId: 'treat_severe_init', color: 'red' },
        ],
        severity: 'info',
    },

    // ── MILD ──────────────────────────────────
    treat_mild_init: {
        id: 'treat_mild_init', type: 'treatment',
        title: '💊 טיפול ראשוני — מקרה קל',
        actions: [
            'בצע הערכה קלינית ומעבדתית מקיפה',
            'חפש זיהומים: תרבית גרון לילד ולכל בני המשפחה — סטרפטוקוק, מיקופלזמה, שמרים. בדוק גם אדמומיות / גרד פריאנלי (סטרפטוקוק פריאנלי)',
            'בזמן ההמתנה לתוצאות: רשום אנטיביוטיקה ל-14 יום (פניצילין / אמוקסיצילין, אזיתרומיצין, צפדיניר, אוגמנטין)',
            'שקול כדורים נוגדי דלקת (NSAIDs) במינון מדכא חיסון ל-5–7 ימים',
            'ודא שלמשפחה יש גישה לטיפול CBT/ERP ותמיכת הורים',
            'קבע פגישת מעקב',
        ],
        options: [{ label: 'מעקב ראשון — כיצד הגיב המטופל? ←', nextId: 'mild_fu1' }],
        severity: 'mild',
    },
    mild_fu1: {
        id: 'mild_fu1', type: 'question',
        title: 'מעקב ראשון — מקרה קל',
        content: 'כיצד הגיב המטופל לטיפול?',
        options: [
            { label: '✅ יש שיפור משמעותי בתסמינים', nextId: 'mild_improved', color: 'green' },
            { label: '⚠️ אין שיפור — התסמינים נשארו', nextId: 'mild_no_improve1' },
        ],
        severity: 'mild',
    },
    mild_improved: {
        id: 'mild_improved', type: 'outcome',
        title: '✅ שיפור — מקרה קל',
        content: 'המטופל הגיב לטיפול. אין צורך בהתערבות נוספת כרגע.',
        actions: ['קבע פגישת מעקב תוך 30 יום (או מוקדם יותר אם התסמינים חוזרים)'],
        severity: 'success',
    },
    mild_no_improve1: {
        id: 'mild_no_improve1', type: 'treatment',
        title: '⚠️ אין שיפור — מעקב ראשון (קל)',
        actions: [
            'בדוק שוב אם יש זיהום פעיל — תרבית לילד ולבני המשפחה, בדוק מיקופלזמה',
            'בדוק האם יש דלקת בסינוסים; שקול משטח לסטרפטוקוק פריאנלי',
            'שקול החלפת אנטיביוטיקה (לאזיתרומיצין, צפדיניר, או אוגמנטין)',
            'שקול מנת סטרואידים קצרה (5 ימים) — או הארכת NSAIDs',
            'ודא שלמשפחה יש גישה לטיפול CBT/ERP; אם הילד לא מסוגל — לימוד כלי ניהול להורים',
            'שקול הפניה לפסיכיאטר לסיוע בניהול התסמינים',
            'קבע פגישת מעקב',
        ],
        options: [{ label: 'מעקב שני — כיצד הגיב המטופל? ←', nextId: 'mild_fu2' }],
        severity: 'mild',
    },
    mild_fu2: {
        id: 'mild_fu2', type: 'question',
        title: 'מעקב שני — מקרה קל',
        content: 'כיצד הגיב המטופל בין שתי הביקורות?',
        options: [
            { label: '🔄 היה שיפור בין הביקורים, אך עדיין יש תסמינים פעילים', nextId: 'mild_partial_improve' },
            { label: '⚠️ אין שיפור כלל', nextId: 'mild_no_improve2' },
        ],
        severity: 'mild',
    },
    mild_partial_improve: {
        id: 'mild_partial_improve', type: 'treatment',
        title: '🔄 שיפור חלקי — מעקב שני (קל)',
        actions: [
            'בדוק שוב זיהום פעיל וחשיפה מאחים, הורים ומגעים קרובים',
            'חדש מרשם אנטיביוטיקה ל-14 ימים נוספים',
            'אם היו 2 הישנויות ומעלה — שקול אנטיביוטיקה מניעתית לטווח ארוך',
            'קבע פגישת מעקב',
        ],
        severity: 'success',
    },
    mild_no_improve2: {
        id: 'mild_no_improve2', type: 'treatment',
        title: '⚠️ אין שיפור — מעקב שני (קל)',
        actions: [
            'שקול מנת סטרואידים קצרה (5 ימים) — או הארכת NSAIDs',
            'בדוק האם התסמינים החמירו לרמה בינונית או חמורה',
            'ודא שלמשפחה יש גישה לטיפול CBT/ERP',
            'שקול הפניה לפסיכיאטר',
            'בצע הערכה מחדש — שקול אבחנה חלופית',
        ],
        options: [{ label: '🟠 התסמינים החמירו? עבור לפרוטוקול בינוני ←', nextId: 'treat_moderate_init', color: 'orange' }],
        severity: 'warning',
    },

    // ── MODERATE ──────────────────────────────
    treat_moderate_init: {
        id: 'treat_moderate_init', type: 'treatment',
        title: '💊 טיפול ראשוני — מקרה בינוני',
        actions: [
            'בצע הערכה קלינית ומעבדתית מקיפה',
            'חפש זיהומים: תרבית גרון לילד ולכל בני המשפחה — סטרפטוקוק (כולל פריאנלי), מיקופלזמה, שמרים',
            'בצע בדיקות מעבדה נוספות לשלילת מצבים אחרים ולכוון הטיפול',
            'רשום אנטיביוטיקה — קורס ראשוני של 3–4 שבועות',
            'רשום מנת סטרואידים קצרה — או NSAIDs ל-5–7 ימים במינון מדכא חיסון',
            'ודא שלמשפחה יש גישה לטיפול CBT/ERP; אם הילד לא מסוגל — לימוד כלי ניהול להורים',
            'שקול הפניה לפסיכיאטר לסיוע בניהול התסמינים',
            'קבע פגישת מעקב',
        ],
        options: [{ label: 'מעקב ראשון — כיצד הגיב המטופל? ←', nextId: 'mod_fu1' }],
        severity: 'moderate',
    },
    mod_fu1: {
        id: 'mod_fu1', type: 'question',
        title: 'מעקב ראשון — מקרה בינוני',
        content: 'כיצד הגיב המטופל לטיפול?',
        options: [
            { label: '✅ יש שיפור משמעותי', nextId: 'mod_improved1', color: 'green' },
            { label: '⚠️ אין שיפור', nextId: 'mod_no_improve1' },
        ],
        severity: 'moderate',
    },
    mod_improved1: {
        id: 'mod_improved1', type: 'outcome',
        title: '✅ שיפור — מעקב ראשון (בינוני)',
        actions: ['קבע פגישת מעקב נוספת ועקוב אחר הישנויות'],
        options: [{ label: 'המשך למעקב שני ←', nextId: 'mod_fu2' }],
        severity: 'success',
    },
    mod_no_improve1: {
        id: 'mod_no_improve1', type: 'treatment',
        title: '⚠️ אין שיפור — מעקב ראשון (בינוני)',
        actions: [
            'החלף אנטיביוטיקה (עבור לאזיתרומיצין, צפדיניר, או אוגמנטין)',
            'בדוק האם יש דלקת בסינוסים; שקול משטח לסטרפטוקוק פריאנלי',
            'אם לא ניסית עדיין — מנת סטרואידים קצרה (5 ימים) או 6 שבועות NSAIDs',
            'שקול ביצוע MRI ו-EEG',
            'שקול בדיקת נוגדנים אנטי-גרעיניים (ANA), נוגדנים נוירונליים ו-CaM Kinase II',
            'קבע פגישת מעקב',
        ],
        options: [{ label: 'המשך למעקב שני ←', nextId: 'mod_fu2' }],
        severity: 'moderate',
    },
    mod_fu2: {
        id: 'mod_fu2', type: 'question',
        title: 'מעקב שני — מקרה בינוני',
        content: 'מה המצב הנוכחי?',
        options: [
            { label: '✅ אין תסמינים פעילים כלל', nextId: 'mod_no_symptoms', color: 'green' },
            { label: '🔄 היה שיפור בין הביקורים, אך עדיין יש תסמינים', nextId: 'mod_partial' },
            { label: '⚠️ אין שיפור כלל', nextId: 'mod_no_improve2' },
        ],
        severity: 'moderate',
    },
    mod_no_symptoms: {
        id: 'mod_no_symptoms', type: 'outcome',
        title: '✅ ללא תסמינים פעילים — בינוני',
        actions: [
            'המשך מעקב לאיתור החמרות עתידיות',
            'הנחה את ההורים להמשיך את טיפול ה-CBT/ERP',
            'אם היו 2 הישנויות ומעלה — שקול אנטיביוטיקה מניעתית לטווח ארוך',
        ],
        severity: 'success',
    },
    mod_partial: {
        id: 'mod_partial', type: 'treatment',
        title: '🔄 שיפור חלקי — מעקב שני (בינוני)',
        actions: [
            'בדוק שוב זיהום פעיל וחשיפה מסביבה קרובה',
            'חדש מרשם אנטיביוטיקה ל-14 ימים',
            'שקול מנת סטרואידים ל-30 יום עם הפחתה הדרגתית — המשך אנטיביוטיקה לאורך כל הטיפול',
            'תאם קבלת IVIG (1.5–2 ג׳/ק״ג על פני יומיים); קבע ביקור מעקב 30 יום לאחר מכן',
            'רשום אנטיביוטיקה מניעתית לאחר השלמת IVIG',
            'אשר שהילד מקבל CBT/ERP ו/או טיפול פסיכיאטרי; דון בציפיות לתוצאות',
        ],
        options: [{ label: 'מעקב לאחר IVIG ←', nextId: 'mod_post_ivig' }],
        severity: 'moderate',
    },
    mod_no_improve2: {
        id: 'mod_no_improve2', type: 'treatment',
        title: '⚠️ אין שיפור — מעקב שני (בינוני)',
        actions: [
            'בדוק האם התסמינים החמירו לרמה חמורה / מסכנת חיים',
            'שקול הפניה דחופה לפסיכיאטר',
            'המשך אנטיביוטיקה — סך משך הטיפול לפחות 30 יום',
            'נסה מנת סטרואידים ל-30 יום עם הפחתה הדרגתית — המשך אנטיביוטיקה לאורך כל הטיפול',
            'הפנה לרופא אא"ג להערכת שקדים ואדנואידים',
            'תאם קבלת IVIG (1.5–2 ג׳/ק״ג על פני יומיים); קבע ביקור מעקב 30 יום לאחר מכן',
        ],
        options: [
            { label: 'מעקב לאחר IVIG ←', nextId: 'mod_post_ivig' },
            { label: '🔴 החמיר? עבור לפרוטוקול חמור', nextId: 'treat_severe_init', color: 'red' },
        ],
        severity: 'warning',
    },
    mod_post_ivig: {
        id: 'mod_post_ivig', type: 'question',
        title: 'מעקב לאחר IVIG — בינוני',
        content: 'כיצד הגיב המטופל לאחר IVIG?',
        options: [
            { label: '✅ שיפור משמעותי / החלמה מלאה', nextId: 'mod_ivig_good', color: 'green' },
            { label: '🔄 שיפור מתון', nextId: 'mod_ivig_modest' },
            { label: '⚠️ אין שיפור', nextId: 'mod_ivig_none' },
        ],
        severity: 'moderate',
    },
    mod_ivig_good: {
        id: 'mod_ivig_good', type: 'outcome',
        title: '✅ שיפור / החלמה לאחר IVIG — בינוני',
        actions: [
            'הנחה את ההורים להמשיך CBT/ERP לתסמינים שנותרו',
            'רשום אנטיביוטיקה מניעתית לטווח ארוך בעקבות ה-IVIG',
        ],
        severity: 'success',
    },
    mod_ivig_modest: {
        id: 'mod_ivig_modest', type: 'treatment',
        title: '🔄 שיפור מתון לאחר IVIG — בינוני',
        actions: [
            'הנחה את ההורים להמשיך CBT/ERP',
            'רשום אנטיביוטיקה מניעתית לטווח ארוך',
            'המשך מעקב תקופתי לאיתור החמרות',
        ],
        severity: 'moderate',
    },
    mod_ivig_none: {
        id: 'mod_ivig_none', type: 'treatment',
        title: '⚠️ אין שיפור לאחר IVIG — בינוני',
        actions: [
            'חזור על הבדיקות האבחנתיות — בדוק האם התסמינים החמירו',
            'שקול IVIG נוסף — או הפניה למרכז להערכת פלזמהפרזיס (טיהור פלזמת הדם)',
            'רשום אנטיביוטיקה מניעתית תוך תיאום הטיפול',
            'הנחה את ההורים להמשיך CBT/ERP',
            'שקול אבחנה חלופית — ייתכן מצב אחר',
        ],
        severity: 'warning',
    },

    // ── SEVERE ────────────────────────────────
    treat_severe_init: {
        id: 'treat_severe_init', type: 'treatment',
        title: '💊 טיפול ראשוני — מקרה חמור / קיצוני',
        actions: [
            'בצע הערכה קלינית ומעבדתית מקיפה',
            'חפש זיהומים: תרבית גרון לילד ולכל בני המשפחה — סטרפטוקוק (כולל פריאנלי), מיקופלזמה, שמרים',
            'הזמן בדיקות מעבדה נוספות לשלילת מצבים אחרים',
            'לחולים עם ARFID — הערך צורך באשפוז בשל ירידת משקל חמורה או עירוי נוזלים',
            'רשום מנת סטרואידים — או NSAIDs ל-5–7 ימים במינון מדכא חיסון',
            'התחל בתיאום קבלת IVIG (1.5–2 ג׳/ק״ג על פני יומיים) — אל תדחה',
            'רשום אנטיביוטיקה — קורס ראשוני של 3–4 שבועות',
            'שקול הפניה לפסיכיאטר לסיוע בניהול התסמינים',
            'קבע שיחת מעקב טלפונית בעוד 5 ימים ופגישת מעקב',
        ],
        options: [{ label: 'שיחת מעקב טלפונית (~5 ימים) — כיצד הגיב? ←', nextId: 'severe_phone' }],
        severity: 'severe',
    },
    severe_phone: {
        id: 'severe_phone', type: 'question',
        title: 'שיחת מעקב טלפונית — מקרה חמור',
        content: 'מעקב טלפוני כ-5 ימים לאחר ההערכה הראשונית — כיצד הגיב המטופל?',
        options: [
            { label: '✅ יש שיפור משמעותי', nextId: 'severe_phone_good', color: 'green' },
            { label: '⚠️ אין שיפור', nextId: 'severe_phone_none' },
        ],
        severity: 'severe',
    },
    severe_phone_good: {
        id: 'severe_phone_good', type: 'treatment',
        title: '✅ שיפור בשיחת מעקב (חמור)',
        actions: [
            'ודא שלמשפחה יש גישה לטיפול CBT/ERP; אם הילד לא מסוגל — לימוד כלי ניהול להורים',
            'אשר שפגישת המעקב נקבעה',
        ],
        options: [{ label: 'פגישת מעקב ←', nextId: 'severe_fu' }],
        severity: 'moderate',
    },
    severe_phone_none: {
        id: 'severe_phone_none', type: 'treatment',
        title: '⚠️ אין שיפור בשיחת מעקב (חמור)',
        actions: [
            'שקול סטרואידים ממושכים (30 יום) עם הפחתה הדרגתית — המשך אנטיביוטיקה לאורך כל הטיפול',
            'שקול החלפת אנטיביוטיקה (לאזיתרומיצין, צפדיניר, או אוגמנטין)',
            'הפנה לרופא אא"ג להערכת שקדים ואדנואידים',
            'שקול IVIG (1.5–2 ג׳/ק״ג על פני יומיים) — אל תדחה יותר',
            'בהתאם לחומרה ובטיחות — שקול אשפוז, או הפניה למרכז המתמחה בהפרעות נוירו-אימוניות',
            'אשר שפגישת המעקב נקבעה',
        ],
        options: [{ label: 'פגישת מעקב ←', nextId: 'severe_fu' }],
        severity: 'severe',
    },
    severe_fu: {
        id: 'severe_fu', type: 'question',
        title: 'פגישת מעקב — מקרה חמור',
        content: 'כיצד הגיב המטופל?',
        options: [
            { label: '✅ יש שיפור משמעותי', nextId: 'severe_improved', color: 'green' },
            { label: '⚠️ אין שיפור', nextId: 'severe_no_improve' },
        ],
        severity: 'severe',
    },
    severe_improved: {
        id: 'severe_improved', type: 'treatment',
        title: '✅ שיפור בפגישת מעקב (חמור)',
        actions: [
            'שקול אנטיביוטיקה מניעתית לטווח ארוך',
            'אם ניתנו NSAIDs — המשך במינון מדכא חיסון לסך כולל של 6–8 שבועות',
            'שקול מתן מעכבי משאבת פרוטון (PPI — כגון אומפרזול) למניעת נזק לקיבה בזמן NSAIDs',
            'אם השתפר אך לא חזר למצב הבסיסי — תאם IVIG, קבע ביקור מעקב 30 יום לאחר מכן',
        ],
        options: [{ label: 'מעקב לאחר IVIG ←', nextId: 'severe_post_ivig' }],
        severity: 'moderate',
    },
    severe_no_improve: {
        id: 'severe_no_improve', type: 'treatment',
        title: '⚠️ אין שיפור בפגישת מעקב (חמור)',
        actions: [
            'החלף אנטיביוטיקה — סך משך הטיפול לפחות 30 יום',
            'בדוק האם יש דלקת בסינוסים; שקול משטח לסטרפטוקוק פריאנלי',
            'מנת סטרואידים ממושכת (30 יום) עם הפחתה הדרגתית — המשך אנטיביוטיקה לכל אורך הטיפול',
            'שקול בדיקת נוגדנים אנטי-גרעיניים, נוגדנים נוירונליים ו-CaM Kinase II',
            'שקול אשפוז, או הפניה למרכז המתמחה בהפרעות נוירו-אימוניות',
            'תאם קבלת IVIG (1.5–2 ג׳/ק״ג על פני יומיים); קבע ביקור מעקב 30 יום לאחר מכן',
        ],
        options: [{ label: 'מעקב לאחר IVIG ←', nextId: 'severe_post_ivig' }],
        severity: 'severe',
    },
    severe_post_ivig: {
        id: 'severe_post_ivig', type: 'question',
        title: 'מעקב לאחר IVIG — חמור',
        content: 'כיצד הגיב המטופל לאחר IVIG?',
        options: [
            { label: '✅ החלמה מלאה', nextId: 'severe_ivig_full', color: 'green' },
            { label: '🔄 שיפור מתון — פחות מ-50% מהתסמינים נעלמו', nextId: 'severe_ivig_modest' },
            { label: '⚠️ אין שיפור', nextId: 'severe_ivig_none' },
        ],
        severity: 'severe',
    },
    severe_ivig_full: {
        id: 'severe_ivig_full', type: 'outcome',
        title: '✅ החלמה מלאה לאחר IVIG — חמור',
        actions: [
            'הפנה למטפל המתמחה ב-פאנס לצורך CBT/ERP לתסמינים שנותרו ולניהול החמרות עתידיות',
            'רשום אנטיביוטיקה מניעתית לטווח ארוך בעקבות ה-IVIG',
        ],
        severity: 'success',
    },
    severe_ivig_modest: {
        id: 'severe_ivig_modest', type: 'treatment',
        title: '🔄 שיפור מתון לאחר IVIG — חמור',
        actions: [
            'הפנה למטפל המתמחה ב-פאנס לצורך CBT/ERP לתסמינים שנותרו',
            'רשום אנטיביוטיקה מניעתית לטווח ארוך',
            'שקול IVIG שני — כ-90 יום לאחר ה-IVIG הראשון',
        ],
        severity: 'moderate',
    },
    severe_ivig_none: {
        id: 'severe_ivig_none', type: 'outcome',
        title: '⚠️ אין שיפור לאחר IVIG — חמור',
        actions: [
            'שקול הפניה למרכז לביצוע פלזמהפרזיס (טיהור פלזמת הדם) — רשום אנטיביוטיקה מניעתית תוך תיאום',
            'שקול אפשרויות טיפול נוספות — pandasppn.org',
            'הפנה למרכז המתמחה בהפרעות נוירו-אימוניות',
            'בצע הערכה מחדש — שקול אבחנה חלופית',
        ],
        severity: 'warning',
    },
};